smugh/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

admin.autodiscover()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # Redirect your homepage
        path('', RedirectView.as_view(url='task/')),

        # app tasks global links
        path('task/', include('tasks.urls'), name='tasks'),

        # admin link
        path('admin/', admin.site.urls),
    ]

tasks/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, include
from tasks.views import *

app_name = 'tasks'
urlpatterns = [
    # url list
    path('', TasksView.as_view(), name='tasks-list'),
    # url delete
    path('delete/', clear_resolved_tasks, name="tasks-clear"),
    # all url finish
    path('toggle/', toggle_tasks, name="tasks-toggle"),

    # url add
    path('add/', TaskCreateView.as_view(), name='task-create'),
    # url finish
    path('toggle/<task_id>/', toggle_task, name="task-toggle"),
    # delete url finish
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name="task-delete"),

    # download url
    path('download/', task_download, name="task-download"),
]

tasks/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

# my models here.
class Task(models.Model):
    content = models.CharField(_(u'task'), max_length=225, null=True, blank=True)
    is_resolved = models.BooleanField(_(u'Resolved ?'), null=True, blank=True)

    def __str__(self):
        return u'Task %d : %s' % (self.id, self.content)

tasks/forms.py
# -*- coding: utf-8 -*-

from django import forms
from tasks.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        # genere resolved a un autre endroit
        exclude = ('is_resolved',)

tasks/views.py
# -*- coding: utf-8 -*-

from django.core.files.storage import FileSystemStorage
from django.views.generic import ListView, CreateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string

from weasyprint import HTML

from tasks.models import Task
from tasks.forms import TaskForm

TASK_LIST_URL = reverse_lazy('tasks:tasks-list')

# Management for the Tasks
class TasksView(ListView):
    template_name = "tasks/tasks-list.html"
    model = Task

# delete the task finished
def clear_resolved_tasks(request):
    if request.method == 'POST':
        # Modify an object in POST only
        Task.objects.filter(is_resolved=True).delete()

    return HttpResponseRedirect(TASK_LIST_URL)


# all tasks finish view
def toggle_tasks(request):
    if request.method == 'POST':
        # Modify an object in post only
        try:
            task = Task.objects.all()[0]
        except IndexError:
            task = None

        if task is not None:
            status = not task.is_resolved
            Task.objects.all().update(is_resolved=status)

    return HttpResponseRedirect(TASK_LIST_URL)


# Gestion du formulaire forms.py
class TaskCreateView(CreateView):
    form_class = TaskForm
    success_url = TASK_LIST_URL

    def form_invalid(self, form):
        # erreurs du formulaire non affiché
        return HttpResponseRedirect(self.success_url)


# task finish view
def toggle_task(request, task_id):
    if request.method == 'POST':
        # Modify an object in post only
        task = get_object_or_404(Task, pk=task_id)

        task.is_resolved = not task.is_resolved
        task.save()

    return HttpResponseRedirect(TASK_LIST_URL)

# delete view
class TaskDeleteView(DeleteView):
    model = Task
    success_url = TASK_LIST_URL

# download view
def task_download(request):
    if 'download-file' in request.method == 'POST':
        task = request.get_object(file='download-file')

    html_template = render_to_string('tasks/tasks-list.html')
    pdf_file = HTML(string=html_template).write_pdf(target="/tmp/task-list.pdf");

    file_system = FileSystemStorage('/tmp')
    with file_system.open('task-list.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'inline; filename="task.pdf"'
        return response

    return response

tasks/templates/tasks/tasks-list.html
{% load i18n staticfiles %}
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% trans "Tasks list" %}</title>
        <link rel="stylesheet" type="text/css" href="{% static "tasks/vendor/css/tasks.min.css" %}">
    </head>


    <body>
        <section id="todoapp">
            <header id="header">
                <h1>{% trans "Todo tasks" %}</h1>
                <form action="{% url "tasks:task-create" %}" method="post">
                    {% csrf_token %}
                    <input id="new-todo" placeholder="{% trans "What needs to be done ?" %}" name="content" autofocus>
                </form>

            </header><!-- ./ end header -->

            <section id="main">
                <form action="{% url 'tasks:tasks-toggle' %}" method="post">
                    {% csrf_token %}
                    <input id="toggle-all" type="checkbox" onclick="this.parentNode.submit();"></input>
                </form>
                <label for="toggle-all"> {% trans "Mark all as complete" %}</label>

                <ul id="todo-list">
                    <!-- all tasks liste -->
                    {% for task in object_list %}
                        <li{% if task.is_resolved %} class="completed"{% endif %}>
                            <div class="view">
                                <form method="post" action="{% url "tasks:task-toggle" task.id %}" >
                                    {% csrf_token %}
                                   <input class="toggle" type="checkbox"{% if task.is_resolved %} checked="checked"{% endif %} onclick="this.parentNode.submit();">
                                </form>

                                <label>{{ task.content }}</label>

                                <form method="post" action="{% url "tasks:task-delete" task.id  %}" >
                                    {% csrf_token %}
                                    <button class="destroy" onclick="this.parentNode.submit();"></button>
                                </form>
                            </div>
                            <input class="edit" value="{{ task.content }}"></input>
                        </li>
                    {% endfor %}
                </ul>
            </section><!-- ./ end main -->

            <footer id="footer">
                <form action="{% url "tasks:tasks-clear" %}" method="post">
                    {% csrf_token %}
                    <button id="clear-complete" onclick="this.parentNode.submit();">{% trans "Clear completed" %}</button>
                </form>
            </footer><!-- ./ end footer -->
        </section><!-- ./ end section -->

        <footer id="info">
            <form action="{% url "tasks:task-download" %}" method="get">
                {% csrf_token %}
                <input type="submit" name="download-file" value="{% trans "Download this file PDF" %}">
            </form>
        </footer><!-- ./ end footer -->

    </body>
</html>